#include "FooFixture.hpp"

void RvoidPintCaller();
void RvoidPint(int);
void RvoidPint_2(int);

void fake_RvoidPint(int a); // user provides
// should be generated by a macro
void fake_RvoidPint_aux(int count, ...) {
    ::ftest::called.insert(reinterpret_cast<char *>(fake_RvoidPint_aux));

    EXPECT_EQ(count, 1);

    va_list args;
    va_start(args, count);
    fake_RvoidPint(va_arg(args, int));
    va_end(args);
}

// User provides
void fake_RvoidPint(int a) {
    ::ftest::called.insert(reinterpret_cast<char *>(fake_RvoidPint));
    EXPECT_EQ(a, 13);
}

/// signature: void(int)
TEST_F(FooFixture, RvoidPint) {
    ::fake::subs.insert({address(RvoidPint), address(fake_RvoidPint_aux)});
    RvoidPintCaller();

    EXPECT_EQ(::ftest::called.count(address(RvoidPint)), 0);
    EXPECT_EQ(::ftest::called.count(address(fake_RvoidPint_aux)), 1);
    EXPECT_EQ(::ftest::called.count(address(fake_RvoidPint)), 1);
    EXPECT_EQ(::ftest::called.count(address(RvoidPint_2)), 1);
}
